name: Build iPhone-VCAM (Theos) arm64 DEB

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos toolchain
        run: |
          git clone --depth 1 https://github.com/theos/theos.git ~/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build and package (arm64)
        run: |
          make clean
          make package ARCHS=arm64

      - name: Rename deb package
        run: |
          TAG_VER=${{ github.event.release.tag_name }}
          find ./packages -type f -name "*.deb" -exec mv {} ./iPhone-VCAM_${TAG_VER}_arm64.deb \;

      - name: Upload to Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: iPhone-VCAM_*_arm64.deb
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
